spring:
  #  batch:
  #    job:
  #      enabled: false
  #    initialize-schema: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: 'root'
    password: 'Costin.Root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#  sql:
#    init:
#      mode: always
#      platform: mysql
#      continue-on-error: true